[package]
name = "rhombus-instinct"
version = "0.1.0"
authors = ["George Silvis, III <george.iii.silvis@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.4"
piston = "0.39.0"
piston2d-graphics = "0.28.0"
pistoncore-glutin_window = "0.51.0"
piston2d-opengl_graphics = "0.57.0"
